apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://github.com/bosslabs/k8s-experiments.git
    targetRevision: HEAD
    path: argo/utilities/ingress-nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system